name: app_music
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to:
version: 1.0.0+1

environment:
  sdk: '>=3.1.0-2.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  json_serializable: ^6.7.1
  flutter_spinkit: ^5.2.0
  cupertino_icons: ^1.0.2
  just_audio: ^0.9.34
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.1
  http: ^1.1.0
flutter_native_splash:
  android: true
  ios: true
  background_image: "assets/bg_splash.jpg"
  image: 'assets/splash.png'
  android_12:
    background_image: assets/bg_splash.jpg
    image: assets/splash.png

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/



