name: app_music
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to:
version: 1.0.0+1

environment:
  sdk: '>=3.1.0-2.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  json_serializable: ^6.7.1
  flutter_spinkit: ^5.2.0
  cupertino_icons: ^1.0.2
  just_audio: ^0.9.34
  dio: ^5.2.1+1
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.1
  http: ^1.1.0
  miniplayer: ^1.0.1
  sliding_up_panel2: ^3.3.0+1
  icons_launcher: ^2.1.3
  google_sign_in: ^6.1.4
  firebase_auth: ^4.7.2
  curved_navigation_bar: ^1.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter

icons_launcher:
  image_path: "assets/logo.png"
  platforms:
    android:
      enable: true


flutter_native_splash:
  android: true
  background_image: "assets/bg_splash.jpg"
  background_image_android: "assets/bg_splash.jpg"
  image: assets/logoSpotify.png
  android_12:
    image: assets/logoSpotify.png

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/



